### ISSUE TITLE
edgetx.sdcard.version contains wrong version reference

### ISSUE THREAD

**Issue by ror1948** [EdgeTX/edgetx-sdcard#102]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Other (Please specify below)

### Current Behavior

SDCARD contents with text file edgetx.sdcard.version in the root contains 2.8 instead of 2.8.1

### Expected Behavior

no effect noticed.
just incorrect documentation.

### Steps To Reproduce

just open file edgetx.sdcard.version and look at version number stated

### Version

Other (Please specify below)

### Transmitter

Radiomaster TX16S / TX16SMK2

### Anything else?

2.8.1

**Comment by pfeerick** [comment]
Also, please keep in mind it IS actually correct - did you install a 2.8.1 sound pack? ;)

**Comment by ror1948** [comment]
NoWhy does it matter?ThanksOn Feb 26, 2023 10:55 p.m., Peter Feerick ***@***.***> wrote:
Also, please keep in mind it IS actually correct - did you install a 2.8.1 sound pack? ;)

**Comment by pfeerick** [comment]
Um... because `edgetx.sdcard.version` describes the version of the sd card pack, not the version of edgetx?
