### ISSUE TITLE
SerialPower Widget return error

### ISSUE THREAD

**Issue by pierrotm777** [EdgeTX/edgetx-sdcard#109]
The actual SerialPower widget version return me an error on my Tx16s simulator
![SerialPower_Tx16s](https://github.com/EdgeTX/edgetx-sdcard/assets/8189970/948fcf16-6250-409a-9c98-21c183fa7863)

**Comment by pfeerick** [comment]
What version of EdgeTX are you running? i.e. This is not available in 2.8 - is a capability which will be introduced in 2.9. 

If this is happening on a nightly build of EdgeTX or recent github companion build, it seems like you found a bug 🐛
