### ISSUE TITLE
TX12 MKII missing in scard.json

### ISSUE THREAD

**Issue by kvaDrug** [EdgeTX/edgetx-sdcard#110]
When I try to update SD card content for my Radiomaster TX12 MK2, I'm getting this errors in the loader:

> Processing updates for: SD Card
> Radio flavour tx12mk2 not listed in sdcard.json
> SD Card preparation failed

Obviously `bw128x64` should be suitable for this model, and sdcard.json contains this entry:
`["RadioMaster TX12", "tx12-", "bw128x64"],`

But something is still wrong. Please, fix :)

**Comment by pfeerick** [comment]
Thanks for the report... it should be fixed now for `latest`
