### ISSUE TITLE
Wrong version set in the edgetx.sdcard.version for 

### ISSUE THREAD

**Issue by ajghor** [EdgeTX/edgetx-sdcard#116]
The version number inside the edgetx.sdcard.version is still 2.8?
Is this a typo only or a wrong version?
I have checked the files in the 2.8 folder and the new 2.9, and there are differences, so it seems to me that this is wrong.

**Comment by pfeerick** [comment]
Someone didn't update the version string... fixing that 😆 Thanks for pointing that out so soon!
