### ISSUE TITLE
LibGUI widget bug

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx-sdcard#136]
demo widget fails at the following line due to 

```lua
local lastSwitch = getSwitchIndex(CHAR_TRIM .. "Rl") - 1
```

no longer being correct in 2.10, due to trim names being changed. 

Should just need changing to a valid name - will just need to check what is a more suitable one.

**Comment by offer-shmuely** [comment]
I think that fixed on pr

https://github.com/EdgeTX/edgetx-sdcard/pull/140

**Comment by pfeerick** [comment]
Indeed. Thanks!
