### ISSUE TITLE
DSM forwarding Program v0.57 (color) issues

### ISSUE THREAD

**Issue by orstratcat** [EdgeTX/edgetx-sdcard#159]
I recently updated my Spektrum AR631 rx to ver 3. Now the DSM Forwarding prog v0.57 (color) reads error 
Invalid TX ch Conf 1
Invalid TX ch Conf 2
If I use the "DSM Smart RX Telemetry" I can see the AS3X, Safe, Esc Status, Battery Status, TextGen, Flight Log boxes, but I cannot change anything, no adjusting roll angles, etc. Also no 1st time gyro set-up after resetting the AR631 rx. Any help would be greatly appreciated!

Using the Radiomaster TX16S MK II EdgeTX v2.10.2

**Comment by pfeerick** [comment]
Is probably better to hassle Frankie directly over at https://github.com/frankiearzu/DSMTools as the DSM Forward Programming tool is actually his - not an EdgeTX project ;)
