### ISSUE TITLE
EL18 support more Theme LUA“320*480”

### ISSUE THREAD

**Issue by fxk666** [EdgeTX/edgetx-sdcard#161]
Which LUA can support in EL18？

**Comment by pfeerick** [comment]
I'm not sure the question... Lua or themes (as the title says themes and lua?) If you want themes... you want to look at https://github.com/EdgeTX/themes

EL18 / 320x480 has always had a much more limited audience, so there are very few Lua scripts that are specifically adapted for that screen orientation / and touch only nature. https://github.com/yaapu/FrskyTelemetryScript and https://github.com/iNavFlight/OpenTX-Telemetry-Widget are the only two big ones I know of... ELRS Lua should work just fine also.

**Comment by fxk666** [comment]
I am looking for a way to reproduce this situation. Thank you for your reply



---Original---
From: "Peter ***@***.***&gt;
Date: Thu, Jul 25, 2024 14:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [EdgeTX/edgetx-sdcard] EL18 support more Theme LUA“320*480” (Issue #161)




 
I'm not sure the question... Lua or themes (as the title says themes and lua?) If you want themes... you want to look at https://github.com/EdgeTX/themes
 
EL18 / 320x480 has always had a much more limited audience, so there are very few Lua scripts that are specifically adapted for that screen orientation / and touch only nature. https://github.com/yaapu/FrskyTelemetryScript and https://github.com/iNavFlight/OpenTX-Telemetry-Widget are the only two big ones I know of... ELRS Lua should work just fine also.

**Comment by pfeerick** [comment]
What situation are you trying to reproduce?
