### ISSUE TITLE
Wizards: Delta Wing Wizard

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx-sdcard#26]
There was a request for a delta wing wizard

**Comment by offer-shmuely** [comment]
I do not have a wing, but still like to try and do that.
What is needed for a wing?

- Motor - yes/no
- Elevron - always
- Dual rate -yes/no
- safety switch on SF (if motor exist) 

What more?

**Comment by pfeerick** [comment]
The primary difference will be be the elevons, and no aileron/elevator/flaps, so yeah, pretty much what you listed. I find it interesting the model wizard in Companion asks if there is a rudder. It's not common, but It does seem to be a thing.

**Comment by offer-shmuely** [comment]
PR #107

**Comment by offer-shmuely** [comment]
![image](https://user-images.githubusercontent.com/7026911/234721699-f6087dc1-c61d-4c0a-80a0-2f665cb452d6.png)

![image](https://user-images.githubusercontent.com/7026911/234721752-fa8f4027-b9a7-4404-ba1d-d45260cbb761.png)
![image](https://user-images.githubusercontent.com/7026911/234721776-319a61e6-e5b2-4dad-8740-efadbde7aa89.png)
![image](https://user-images.githubusercontent.com/7026911/234721806-20d46fcc-0656-4c6b-9333-475871e743b4.png)
![image](https://user-images.githubusercontent.com/7026911/234721954-83bb2312-8884-4a8c-a31a-b17fffd8fa23.png)
![image](https://user-images.githubusercontent.com/7026911/234722033-40391fec-fba0-4493-bc65-0a22684d93fc.png)
![image](https://user-images.githubusercontent.com/7026911/234722060-c2a8d7da-340c-4034-a7b1-f5c241beb99c.png)

**Comment by offer-shmuely** [comment]
Is it worth to add a model name as well to the wizard?

**Comment by offer-shmuely** [comment]
will be closed when #107 will be merged
