### ISSUE TITLE
Missing my ISRM-Module with FrSky-X12S

### ISSUE THREAD

**Issue by wollenagold** [EdgeTX/edgetx-sdcard#39]
Hi guys
Changing on to EdgeTX i don't find my internal Access-Module when i'm opening the internal RF-selection, only XJT is displayed or OFF.
Is it possible that i put a wrong Version of 2.5.0 Dauntless? Functionally has been ok, only the RF-selection has an issue.

Today, one day later new attempt:
Changing back to OpenTX 2.3.14 with changing the Models- and Radio-Directorys from the back-up will give me back the complete functionally of the ISRM-Modul inside the TX under OTX. The HF-Links to the receivers are all ok.

Thank you for Help which make me able to can try it again with Edge.
Wolfgang

**Comment by pfeerick** [comment]
Wrong repo, and I believe this was resolved over in EdgeTX/edgetx/issues/1297. If you are still having issues, [please join us on Discord](https://discord.gg/wF9wUKnZ6H) and we'll work through it.
