### ISSUE TITLE
Lua script for Open Location (Google+) Code

### ISSUE THREAD

**Issue by ChrisOhara57** [EdgeTX/edgetx-sdcard#40]
To Peter Feerick

sorry I didn't succeed in putting a pull request.
Here is the Zip file.

I tested the code on my Taranis x9lite S.
I think it should run as a telemetry script on all black and white screens.

**Sorry I didn't mention that I have only tested on openTx.
But it's a simple script that should run also on EdgeTX**

Thanks Chris

[gplusl.zip](https://github.com/EdgeTX/edgetx-sdcard/files/7781723/gplusl.zip)

**Comment by pfeerick** [comment]
I haven't forgotten this, and will add it in the next couple of days. I just wanted to draw to your attention that it looks like there is also a widget for colorlcd radios as well ;) https://github.com/kristjanbjarni/opentx-widgets

**Comment by ChrisOhara57** [comment]
Thanks for the info (at the moment I only use a x9lite) but it's good to know.
If you think there is no need for a second script, feel free to dismiss it.

**Comment by pfeerick** [comment]
I just double checked it on X9D and TPro simulator, and it seems to work fine on ETX also. I've added a commit adding this with you as the commit author.
