### ISSUE TITLE
Additional default widgets

### ISSUE THREAD

**Issue by bakwc** [EdgeTX/edgetx-sdcard#44]
Hi guys! Do you accept a new default widgets in addition to the existing?

I have found a few [really nice widgets](https://github.com/kristjanbjarni/opentx-widgets) and I suggest to add some of them by default (eg. home distance + home direction arrow).
Is it make sense to check and port them to edgetx? Will you accept them?

**Comment by pfeerick** [comment]
Of course, when it makes sense to include them... just have to be careful not to get too crazy with adding them. Most likely those widgets will just run, or only require minor changes. 

You are also welcome to make a PR to https://github.com/EdgeTX/lua-scripts adding those widgets to the list.
