### ISSUE TITLE
Theme Cappuccino

### ISSUE THREAD

**Issue by ParkerEde** [EdgeTX/edgetx-sdcard#55]
Hi,
I've created a theme RK-Cappuccino.
So if you like, you can push it to the SD Card repo.
Kind regards
![image](https://user-images.githubusercontent.com/15068446/157428249-a877c533-459f-4b22-8b66-5e8d5524c6a1.png)
![image](https://user-images.githubusercontent.com/15068446/157428340-16831be8-9487-4fb3-90fe-2bc8b9e02d77.png)
![image](https://user-images.githubusercontent.com/15068446/157428428-250d4df4-3630-487e-98c2-3638c21c5dcd.png)

[RK_Cappuccino.zip](https://github.com/EdgeTX/edgetx-sdcard/files/8214022/RK_Cappuccino.zip)

**Comment by pfeerick** [comment]
I'll add this to the [themes library](https://github.com/EdgeTX/themes)... you'll have some coffee competition as there's already [InGage_coffee ](https://github.com/EdgeTX/themes#ingage_coffee) and [InGage_Espresso](https://github.com/EdgeTX/themes#ingage_espresso)
