### ISSUE TITLE
Folder names

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx-sdcard#6]
Hi guys.

To make names  radio agnostic i propose:
horus -> 480x272
nv14 -> 320x480
taranis-x7 -> 128x64
taranis-x9 -> 212x64

**Comment by CoderElectronics** [comment]
I would prefer to leave it as it is currently because of the flasher but I will take a look at changing that soon.

**Comment by JimB40** [comment]
Okay but include it in TODO.
Horus is not only one color one now nor most popular :)

**Comment by pfeerick** [comment]
Closing as was done in #65
