### ISSUE TITLE
480x272 obsolete theme folders scratch

### ISSUE THREAD

**Issue by JimB40** [EdgeTX/edgetx-sdcard#7]
Only default theme in 2.4 so these may be dumped to save download time
/THEMES/Darkblue
/THEMES/Default
/THEMES/Flexi

**Comment by CoderElectronics** [comment]
Ok I will remove those. Thank you!

**Comment by CoderElectronics** [comment]
All fixed here: https://github.com/EdgeTX/edgetx-sdcard/commit/eba02901f48ce04a9a5f4fca123bc534fb28211e
