### ISSUE TITLE
wizard Heli EdtgeTx 2.8.0

### ISSUE THREAD

**Issue by ffvamp69** [EdgeTX/edgetx-sdcard#89]
Hello, do you know anything about when we will have a helicopter wizard for EdgeTx 2.8.0 onwards?
Thank you

**Comment by pfeerick** [comment]
Helli wizard is now in the 'latest' release for the sd card pack, pending inclusion in a future versioned release.

**Comment by ffvamp69** [comment]
Thank you and I look forward to it

**Comment by pfeerick** [comment]
You can safely grab it now if you use the 'latest' release of the SD card pack ;) https://github.com/EdgeTX/edgetx-sdcard/releases/tag/latest
